language: node_js
node_js: '11'
cache: npm

install: 
  - npm install

script: npm run deploy

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  repo: fredvisser/design-system
  target_branch: gh-pages
  on:
    branch: master
  local_dir: public 